### ISSUE TITLE
1.2.4 container failing to start

### ISSUE THREAD

**Issue by pgier** [datastax/pulsar-admin-console#45]
The latest release of the admin-console container image seems to be failing to start.  The container logs some error messages and then fails.  This issue doesn't happen in the 1.2.3 container, is there some new configuration that is required for 1.2.4, or is this just a bad build of the container?

```

> backend@0.0.1 start /home/appuser/server
> node server.js

info: server config  {"auth_mode":"k8s","timestamp":"2022-02-14T21:04:41.549Z","token_path":"/pulsar/token-superuser/superuser.jwt"}
internal/modules/cjs/loader.js:905
  throw err;
  ^

Error: Cannot find module 'brace-expansion'
Require stack:
- /home/appuser/server/node_modules/glob/node_modules/minimatch/minimatch.js
- /home/appuser/server/node_modules/glob/glob.js
- /home/appuser/server/node_modules/shelljs/src/common.js
- /home/appuser/server/node_modules/shelljs/shell.js
- /home/appuser/server/node_modules/@kubernetes/client-node/dist/config.js
- /home/appuser/server/node_modules/@kubernetes/client-node/dist/index.js
- /home/appuser/server/node_modules/kubernetes-client/lib/config.js
- /home/appuser/server/node_modules/kubernetes-client/lib/swagger-client.js
- /home/appuser/server/node_modules/kubernetes-client/lib/index.js
- /home/appuser/server/k8s.js
- /home/appuser/server/server.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:93:18)
    at Object.<anonymous> (/home/appuser/server/node_modules/glob/node_modules/minimatch/minimatch.js:10:16)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/appuser/server/node_modules/glob/node_modules/minimatch/minimatch.js',
    '/home/appuser/server/node_modules/glob/glob.js',
    '/home/appuser/server/node_modules/shelljs/src/common.js',
    '/home/appuser/server/node_modules/shelljs/shell.js',
    '/home/appuser/server/node_modules/@kubernetes/client-node/dist/config.js',
    '/home/appuser/server/node_modules/@kubernetes/client-node/dist/index.js',
    '/home/appuser/server/node_modules/kubernetes-client/lib/config.js',
    '/home/appuser/server/node_modules/kubernetes-client/lib/swagger-client.js',
    '/home/appuser/server/node_modules/kubernetes-client/lib/index.js',
    '/home/appuser/server/k8s.js',
    '/home/appuser/server/server.js'
  ]
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! backend@0.0.1 start: `node server.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the backend@0.0.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/appuser/.npm/_logs/2022-02-14T21_04_41_708Z-debug.log
```

**Comment by michaeljmarshall** [comment]
@pgier - what command are you using to start the 1.2.4 docker image?

**Comment by pgier** [comment]
@michaeljmarshall we don't have any specific command or args set, so I guess it's just using the default container command/entrypoint.
